/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.DaoEmpleados_apocrifos;
import Dto.Empleados_apocrifos;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jotruvel
 */
public class FrmEmpleados extends javax.swing.JFrame {

    DefaultTableModel modeloEmpleados;

    public void desbloquear() {
        txtid_empleado.setEnabled(rootPaneCheckingEnabled);
        txtnombre.setEnabled(rootPaneCheckingEnabled);
        cbopuesto.setEnabled(rootPaneCheckingEnabled);
        txtcontraseña.setEnabled(rootPaneCheckingEnabled);
        txtcontraseña2.setEnabled(rootPaneCheckingEnabled);
        btnBuscarEmpleado.setEnabled(rootPaneCheckingEnabled);
        btnActualizarEmpleado.setEnabled(rootPaneCheckingEnabled);
        btnelimarEmpleado.setEnabled(rootPaneCheckingEnabled);
        btnGuardarEmpleados.setEnabled(rootPaneCheckingEnabled);
        btnModificar.setEnabled(rootPaneCheckingEnabled);
    }

    public void bloquear() {
        txtid_empleado.setEnabled(!rootPaneCheckingEnabled);
        txtnombre.setEnabled(!rootPaneCheckingEnabled);
        cbopuesto.setEnabled(!rootPaneCheckingEnabled);
        txtcontraseña.setEnabled(!rootPaneCheckingEnabled);
        txtcontraseña2.setEnabled(!rootPaneCheckingEnabled);
        btnBuscarEmpleado.setEnabled(!rootPaneCheckingEnabled);
        btnActualizarEmpleado.setEnabled(!rootPaneCheckingEnabled);
        btnelimarEmpleado.setEnabled(!rootPaneCheckingEnabled);
        btnGuardarEmpleados.setEnabled(!rootPaneCheckingEnabled);

    }

    public void limpiarcasillas() {
        txtid_empleado.setText("");
        txtnombre.setText("");
        txtcontraseña.setText("");
        txtcontraseña2.setText("");
    }

    /**
     * Creates new form FrmEmpleados
     */
    public FrmEmpleados() {
        initComponents();
        this.setLocationRelativeTo(null);

        modeloEmpleados = new DefaultTableModel();
        modeloEmpleados.addColumn("NÚMERO DE EMPLEADO");
        modeloEmpleados.addColumn("NOMBRE");
        modeloEmpleados.addColumn("PUESTO");
        this.tablaEmpleados.setModel(modeloEmpleados);
        DaoEmpleados_apocrifos da = new DaoEmpleados_apocrifos();
        da.buscartabla(tablaEmpleados);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtid_empleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        cbopuesto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcontraseña2 = new javax.swing.JPasswordField();
        txtcontraseña = new javax.swing.JPasswordField();
        btnBuscarEmpleado = new javax.swing.JButton();
        btnGuardarEmpleados = new javax.swing.JButton();
        btnActualizarEmpleado = new javax.swing.JButton();
        btnelimarEmpleado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_filtro = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Nombre empleado: ");

        txtid_empleado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtid_empleado.setForeground(new java.awt.Color(0, 51, 153));
        txtid_empleado.setEnabled(false);
        txtid_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_empleadoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Número empleado: ");

        txtnombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(245, 93, 13));
        txtnombre.setEnabled(false);

        cbopuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASISTENTE", "COORDINADOR", "DIRECTOR", "OTRO" }));
        cbopuesto.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Contraseña: ");

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Puesto: ");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Contraseña: ");

        txtcontraseña2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtcontraseña2.setForeground(new java.awt.Color(0, 51, 153));
        txtcontraseña2.setEnabled(false);

        txtcontraseña.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtcontraseña.setForeground(new java.awt.Color(0, 51, 153));
        txtcontraseña.setEnabled(false);

        btnBuscarEmpleado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscarEmpleado.setText("BUSCAR");
        btnBuscarEmpleado.setEnabled(false);
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        btnGuardarEmpleados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardarEmpleados.setForeground(new java.awt.Color(0, 153, 0));
        btnGuardarEmpleados.setText("GUARDAR");
        btnGuardarEmpleados.setEnabled(false);
        btnGuardarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpleadosActionPerformed(evt);
            }
        });

        btnActualizarEmpleado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizarEmpleado.setText("ACTUALIZAR");
        btnActualizarEmpleado.setEnabled(false);
        btnActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEmpleadoActionPerformed(evt);
            }
        });

        btnelimarEmpleado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnelimarEmpleado.setForeground(new java.awt.Color(255, 0, 0));
        btnelimarEmpleado.setText("ELIMINAR");
        btnelimarEmpleado.setEnabled(false);
        btnelimarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelimarEmpleadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nombre Empleado");

        txt_filtro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_filtro.setForeground(new java.awt.Color(245, 93, 13));
        txt_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filtroActionPerformed(evt);
            }
        });
        txt_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_filtroKeyTyped(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("U-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtid_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnBuscarEmpleado)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizarEmpleado)
                                .addGap(26, 26, 26)
                                .addComponent(btnelimarEmpleado))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcontraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addComponent(btnGuardarEmpleados)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtid_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnBuscarEmpleado)
                    .addComponent(btnActualizarEmpleado)
                    .addComponent(btnelimarEmpleado)
                    .addComponent(jLabel1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtcontraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarEmpleados)
                            .addComponent(btnModificar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("EMPLEADOS", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtid_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_empleadoActionPerformed

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        // Botón buscar empleado

        DaoEmpleados_apocrifos e = new DaoEmpleados_apocrifos();
        Empleados_apocrifos em = e.buscar(txtid_empleado.getText());

        if (txtid_empleado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo vacio");
        } else {
            if (!e.isIsError() && em != null) {
                if (!em.getId_empleado().equals("")) {
                    txtid_empleado.setText(em.getId_empleado());
                    txtnombre.setText(em.getNombre());
                    cbopuesto.setSelectedItem(em.getPuesto());
                    txtcontraseña.setText(em.getContraseña());

                }
            } else {
                JOptionPane.showMessageDialog(null, "NO SE PUEDE ENCONTRAR, ERROR: " + e.getError());
            }
        }
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnGuardarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpleadosActionPerformed
        // Botón Guardar Empleados

        Empleados_apocrifos e = new Empleados_apocrifos();
        e.setId_empleado(txtid_empleado.getText());
        e.setNombre(txtnombre.getText());
        e.setPuesto(cbopuesto.getSelectedItem().toString());
        e.setContraseña(txtcontraseña.getText());
        e.setContraseña2(txtcontraseña2.getText());

        int opcion = JOptionPane.showConfirmDialog(null, "Estas seguro de que quieres guardar el registro", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_NO_OPTION) {
            if (txtcontraseña.getText().equals(txtcontraseña2.getText())) {
                DaoEmpleados_apocrifos da = new DaoEmpleados_apocrifos();
                int res = da.insertar(e);
                if (!da.isIsError() && res != 0) {

                    JOptionPane.showMessageDialog(null, "Se Agrego correctamente. ");
                } else {

                    JOptionPane.showMessageDialog(null, "No se pudo agregar, error: " + da.getError());
                }

                modeloEmpleados.getDataVector().removeAllElements();
                tablaEmpleados.updateUI();
                da.clean();
                da.buscartabla(tablaEmpleados);
                limpiarcasillas();
                bloquear();

            } else {
                JOptionPane.showMessageDialog(null, "LAS CONTRASEÑAS NO SON IGUALES.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No se realizo ninguna modificación");
        }


    }//GEN-LAST:event_btnGuardarEmpleadosActionPerformed

    private void btnActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEmpleadoActionPerformed
        // Botón actualizar registros
        Empleados_apocrifos e = new Empleados_apocrifos();
        e.setId_empleado(txtid_empleado.getText());
        e.setNombre(txtnombre.getText());
        e.setPuesto(cbopuesto.getSelectedItem().toString());
        e.setContraseña(txtcontraseña.getText());
        e.setContraseña2(txtcontraseña2.getText());

        int opcion = JOptionPane.showConfirmDialog(null, "ESTAS SEGURO QUE QUIERES  ACTUALIZAR EL REGISTRO", "CONFIRMAR", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_NO_OPTION) {
            if (txtcontraseña.getText().equals(txtcontraseña2.getText())) {
                DaoEmpleados_apocrifos da = new DaoEmpleados_apocrifos();
                int res = da.actualizar(e);
                if (!da.isIsError() && res != 0) {

                    JOptionPane.showMessageDialog(null, "Se Agrego correctamente. ");
                } else {

                    JOptionPane.showMessageDialog(null, "No se pudo agregar, error: " + da.getError());
                }

                modeloEmpleados.getDataVector().removeAllElements();
                tablaEmpleados.updateUI();
                bloquear();
                limpiarcasillas();

                da.clean();
                da.buscartabla(tablaEmpleados);

            } else {
                JOptionPane.showMessageDialog(null, "LAS CONTRASEÑAS NO SON IGUALES.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No se realizo ninguna modificación");
        }

        JOptionPane.showMessageDialog(null, "SE BLOQUEARAN LAS CASILLAS");


    }//GEN-LAST:event_btnActualizarEmpleadoActionPerformed

    private void btnelimarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelimarEmpleadoActionPerformed
        // botón Eliminar empleado

        int opcion = JOptionPane.showConfirmDialog(null, "Estas seguro que quieres eliminar el registro", "confirmar", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_NO_OPTION) {
            if (txtid_empleado.getText().toString().equals("") || txtid_empleado.getText() == null) {
                Icon m = new ImageIcon(getClass().getResource("/Image/unitec.jpeg"));
                JOptionPane.showMessageDialog(null, "NO SE PUEDE ELIMINAR SI NO HAY MATRICULA");;
            } else {
                DaoEmpleados_apocrifos da = new DaoEmpleados_apocrifos();
                int resultado = da.eliminar(txtid_empleado.getText());
                if (!da.isIsError() || resultado != 0) {
                    Icon m = new ImageIcon(getClass().getResource("/Image/unitec.jpeg"));
                    JOptionPane.showMessageDialog(null, "SE ELIMINO CORRECTAMENTE");
                } else {
                    Icon m = new ImageIcon(getClass().getResource("/Image/unitec.jpeg"));
                    JOptionPane.showMessageDialog(null, "NO SE PUDO ELIMAR EL REGISTRO, error: " + da.getError());
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "NO SE REALIZO NINGUNA MODIFICACIÓN");
        }

        modeloEmpleados.getDataVector().removeAllElements();
        tablaEmpleados.updateUI();
        DaoEmpleados_apocrifos da = new DaoEmpleados_apocrifos();
        da.clean();
        da.buscartabla(tablaEmpleados);
        bloquear();
        limpiarcasillas();
    }//GEN-LAST:event_btnelimarEmpleadoActionPerformed

    private void txt_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filtroActionPerformed
        // Filtrar busqueda

    }//GEN-LAST:event_txt_filtroActionPerformed

    private void txt_filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtroKeyTyped
        // TODO add your handling code here:

        modeloEmpleados.getDataVector().removeAllElements();
        tablaEmpleados.updateUI();
        DaoEmpleados_apocrifos da = new DaoEmpleados_apocrifos();
        da.clean();
        da.filtro(tablaEmpleados, txt_filtro.getText());
    }//GEN-LAST:event_txt_filtroKeyTyped

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // DESBLOQUEAR PARA INGRESAR DATOS Y ACTUALIZAR

        FrmDesbloquearEmpleados f = new FrmDesbloquearEmpleados();
        f.show();
        this.hide();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //BOTÓN PARA REGRESAR AL MENU PRINCIPAL

        FrmMenu f = new FrmMenu();
        f.show();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEmpleado;
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnGuardarEmpleados;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnelimarEmpleado;
    private javax.swing.JComboBox<String> cbopuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txt_filtro;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JPasswordField txtcontraseña2;
    private javax.swing.JTextField txtid_empleado;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
